import React, { useState } from 'react';
import Course from './Course';
import styles from './css/CourseSection.module.css';
import CalendarMonthIcon from '@mui/icons-material/CalendarMonth';
import JSImage from '../../assets/js.png';
import aiImage from '../../assets/ai.png';
import reactImage from '../../assets/react.png';
import wordpressImage from '../../assets/wordpress.png';
import interviewImage from '../../assets/interview.png';
import dsaImage from '../../assets/dsa.png';
import Spinner from '../Animation/Spinner';

const CourseSection = () => {
  const [Courses] = useState([
    {
      _id: "1",
      CourseName: "JavaScript Essentials Course",
      date: "2025-05-01",
      time: "10:00 AM",
      CourseImage: JSImage,
      videoLink: "https://youtu.be/876aSEUA_8c?si=LyYIs-wK0fI5wJ",
      contents: [
        {
          section: "Section 1: Intro to Advanced Topics",
          duration: "17 minutes",
          topics: [
            { time: "0:00:00", title: "Intro" },
            { time: "0:02:18", title: "Why this course works for you?" },
            { time: "0:06:25", title: "Course Materials" },
            { time: "0:12:06", title: "Setting up the Development Environment" },
            { time: "0:17:36", title: "Social Media" }
          ]
        },
        {
          section: "Section 2: Objects",
          duration: "1 hour 22 minutes",
          topics: [
            { time: "0:18:06", title: "What is OOP?" },
            { time: "0:20:06", title: "Four Pillars of OOP" },
            { time: "0:27:11", title: "Object Literals" },
            { time: "0:31:12", title: "Factories" },
            { time: "0:35:12", title: "Constructors" },
            { time: "0:39:44", title: "Constructor Property" },
            { time: "0:40:45", title: "Functions are Objects" },
            { time: "0:44:49", title: "Value vs Reference Types" },
            { time: "0:47:46", title: "Adding or Removing Properties" },
            { time: "0:51:44", title: "Enumerating Properties" },
            { time: "0:57:02", title: "Abstraction" },
            { time: "1:12:22", title: "Private Properties and Methods" },
            { time: "1:35:00", title: "Getters and Setters" },
            { time: "1:39:49", title: "Summary" }
          ]
        },
        {
          section: "Section 3: Prototypes",
          duration: "55 minutes",
          topics: [
            { time: "1:41:02", title: "Inheritance" },
            { time: "1:45:18", title: "Prototypes and Prototypical Inheritance" },
            { time: "2:03:33", title: "Multilevel Inheritance" },
            { time: "2:05:20", title: "Property Descriptors" },
            { time: "2:14:26", title: "Constructor Prototypes" },
            { time: "2:18:00", title: "Prototype vs Instance Members" },
            { time: "2:23:55", title: "Iterating Instance and Prototype Members" },
            { time: "2:28:41", title: "Avoid Extending the Built-in Objects" },
            { time: "2:32:43", title: "Summary" }
          ]
        },
        {
          section: "Section 4: Prototypical Inheritance",
          duration: "54 minutes",
          topics: [
            { time: "2:36:06", title: "Creating Your Own Prototypical Inheritance" },
            { time: "2:47:56", title: "Resetting the Constructor" },
            { time: "2:54:29", title: "Calling the Super Constructor" },
            { time: "2:59:44", title: "Intermediate Function Inheritance" },
            { time: "3:03:51", title: "Method Overriding" },
            { time: "3:08:34", title: "Polymorphism" },
            { time: "3:14:16", title: "When to Use Inheritance" },
            { time: "3:22:11", title: "Mixins" },
            { time: "3:28:22", title: "Summary" }
          ]
        },
        {
          section: "Section 5: ES6 Classes",
          duration: "1 hour 10 minutes",
          topics: [
            { time: "3:30:02", title: "ES6 Classes" },
            { time: "3:37:14", title: "Hoisting" },
            { time: "3:42:39", title: "Static Methods" },
            { time: "3:50:28", title: "The 'this' keyword" },
            { time: "3:56:16", title: "Private Members Using Symbols" },
            { time: "4:12:10", title: "Private Members Using WeakMaps" },
            { time: "4:20:08", title: "Getters and Setters" },
            { time: "4:26:46", title: "Inheritance" },
            { time: "4:33:32", title: "Method Overriding" },
            { time: "4:38:27", title: "Summary" }
          ]
        },
        {
          section: "Section 6: ES6 Tooling",
          duration: "53 minutes",
          topics: [
            { time: "4:40:41", title: "Modules" },
            { time: "4:44:59", title: "CommonJS Modules" },
            { time: "4:45:35", title: "ES6 Modules" },
            { time: "5:05:40", title: "ES6 Tooling" },
            { time: "5:11:21", title: "Babel" },
            { time: "5:22:39", title: "Webpack" },
            { time: "5:32:25", title: "Summary" }
          ]
        },
        {
          section: "Section 7: Node Module System",
          duration: "1 hour 29 minutes",
          topics: [
            { time: "5:33:56", title: "What is Node" },
            { time: "5:36:36", title: "Node Architecture" },
            { time: "5:39:19", title: "How Node Works" },
            { time: "5:44:24", title: "Intro to the Node Module System" },
            { time: "5:50:04", title: "Global Object" },
            { time: "5:55:47", title: "Modules" },
            { time: "6:03:55", title: "Creating a Module" },
            { time: "6:08:58", title: "Loading a Module" },
            { time: "6:14:43", title: "Module Wrapper Function" },
            { time: "6:19:28", title: "Path Module" },
            { time: "6:25:09", title: "OS Module" },
            { time: "6:29:09", title: "File System Module" },
            { time: "6:34:57", title: "Events Module" },
            { time: "6:40:23", title: "Event Arguments" },
            { time: "6:45:50", title: "Extending EventEmitter" },
            { time: "6:53:23", title: "HTTP Module" },
            { time: "7:00:30", title: "Summary" }
          ]
        },
        {
          section: "Section 8: Node Package Manager",
          duration: "1 hour 16 minutes",
          topics: [
            { time: "7:03:00", title: "Intro to the Node Package Manager" },
            { time: "7:08:25", title: "package.json" },
            { time: "7:13:39", title: "Installing a Node Package" },
            { time: "7:18:40", title: "Using a Package" },
            { time: "7:22:22", title: "Package Dependencies" },
            { time: "7:28:26", title: "NPM Packages and Source Control" },
            { time: "7:34:05", title: "Semantic Versioning" },
            { time: "7:39:06", title: "Listing the Installed Packages" },
            { time: "7:43:50", title: "Viewing Registry Info for a Package" },
            { time: "7:47:47", title: "Installing a Specific Version of a Package" },
            { time: "7:51:30", title: "Updating Local Packages" },
            { time: "7:56:37", title: "DevDependencies" },
            { time: "8:01:16", title: "Uninstalling a Package" },
            { time: "8:05:13", title: "Working with Global Packages" },
            { time: "8:10:05", title: "Publishing a Package" },
            { time: "8:15:07", title: "Updating a Published Package" }
          ]
        },
        {
          section: "Section 9: Asynchronous JavaScript",
          duration: "1 hour 12 minutes",
          topics: [
            { time: "8:19:29", title: "Synchronous vs Asynchronous Code" },
            { time: "8:24:34", title: "Patterns for Dealing with Asynchronous Code" },
            { time: "8:35:43", title: "Callbacks" },
            { time: "8:41:52", title: "Callback Hell" },
            { time: "8:53:15", title: "Named Functions" },
            { time: "9:03:47", title: "Promises" },
            { time: "9:09:15", title: "Replacing Callbacks with Promises" },
            { time: "9:12:27", title: "Creating Settled Promises" },
            { time: "9:16:20", title: "Running Promises in Parallel" },
            { time: "9:23:30", title: "Async and Await" },
            { time: "9:28:32", title: "Summary" }
          ]
        }
      ]
    },
    {
      _id: "2",
      CourseName: "Neetcode 150 Course - All Coding Interview Questions Solved",
      date: "2025-06-10",
      time: "09:00 AM",
      CourseImage: interviewImage,
      videoLink: "https://youtu.be/T0u5nwSA0w0?si=GJaDMOimLLloZriB",
      contents: [
        { time: "00:00:00", title: "Intro" },
        { time: "00:02:09", title: "1 Contains Duplicate, 2 Valid Anagram" },
        { time: "00:18:30", title: "3 Two Sum, 4 Group Anagrams" },
        { time: "00:41:05", title: "5 Top K Frequent Elements, 6 Product of Array Except Self" },
        { time: "01:08:33", title: "7 Valid Sudoku, 8 Encode and Decode Strings" },
        { time: "01:35:31", title: "9 Longest Consecutive Sequence, 10 Valid Palindrome" },
        { time: "02:08:13", title: "11 Two Sum II Input Array Is Sorted, 12 3Sum" },
        { time: "02:40:58", title: "13 Container With Most Water, 14 Trapping Rain Water" },
        { time: "03:22:29", title: "15 Best Time to Buy And Sell Stock, 16 Longest Substring w/out Repeating Characters" },
        { time: "03:43:04", title: "17 Longest Repeating Character Replacement, 18 Permutation In String" },
        { time: "04:17:11", title: "19 Minimum Window Substring, 20 Sliding Window Maximum" },
        { time: "04:59:44", title: "21 Valid Parentheses, 22 Min Stack" },
        { time: "05:20:33", title: "23 Evaluate Reverse Polish Notation, 24 Generate Parentheses" },
        { time: "05:45:54", title: "25 Daily Temperatures, 26 Car Fleet" },
        { time: "06:19:22", title: "27 Largest Rectangle In Histogram, 28 Binary Search" },
        { time: "06:46:23", title: "29 Search a 2D Matrix, 30 Koko Eating Bananas" },
        { time: "07:11:21", title: "31 Find Minimum In Rotated Sorted Array, 32 Search In Rotated Sorted Array" },
        { time: "07:37:45", title: "33 Time Based Key Value Store, 34 Median of Two Sorted Arrays" },
        { time: "08:22:13", title: "35 Reverse Linked List, 36 Merge Two Sorted Lists" },
        { time: "08:41:04", title: "37 Reorder List, 38 Remove Nth Node From End of List" },
        { time: "09:07:21", title: "39 Copy List With Random Pointer, 40 Add Two Numbers" },
        { time: "09:33:40", title: "41 Linked List Cycle, 42 Find The Duplicate Number" },
        { time: "09:59:00", title: "43 LRU Cache, 44 Merge K Sorted Lists" },
        { time: "10:33:35", title: "45 Reverse Nodes In K Group, 46 Invert Binary Tree" },
        { time: "10:58:05", title: "47 Maximum Depth of Binary Tree, 48 Diameter of Binary Tree" },
        { time: "11:12:42", title: "49 Balanced Binary Tree, 50 Same Tree" },
        { time: "11:28:36", title: "51 Subtree of Another Tree, 52 Lowest Common Ancestor of a Binary Search Tree" },
        { time: "11:47:38", title: "53 Binary Tree Level Order Traversal, 54 Binary Tree Right Side View" },
        { time: "12:09:32", title: "55 Count Good Nodes In Binary Tree, 56 Validate Binary Search Tree" },
        { time: "12:30:28", title: "57 Kth Smallest Element In a Bst, 58 Construct Binary Tree" },
        { time: "12:53:46", title: "59 Binary Tree Maximum Path Sum, 60 Serialize And Deserialize Binary Tree" },
        { time: "13:20:24", title: "61 Implement Trie Prefix Tree, 62 Design Add And Search Words" },
        { time: "14:01:28", title: "63 Word Search II, 64 Kth Largest Element In a Stream" },
        { time: "14:30:37", title: "65 Last Stone Weight, 66 K Closest Points to Origin" },
        { time: "14:50:44", title: "67 Kth Largest Element In Array, 68 Task Scheduler" },
        { time: "15:19:56", title: "69 Design Twitter, 70 Find Median From Data Stream" },
        { time: "16:15:43", title: "71 Subsets, 72 Combination Sum" },
        { time: "16:15:43", title: "73 Permutations, 74 Subsets II" },
        { time: "16:49:54", title: "75 Combination Sum II, 76 Word Search" },
        { time: "17:16:03", title: "77 Palindrome Partitioning, 78 Letter Combinations of a Phone" },
        { time: "17:44:08", title: "79 N Queens, 80 Number of Islands" },
        { time: "18:12:44", title: "81 Clone Graph, 82 Max Area of Island" },
        { time: "18:54:05", title: "83 Pacific Atlantic Water Flow, 84 Surrounded Regions" },
        { time: "19:21:28", title: "85 Rotting Oranges, 86 Walls And Gates" },
        { time: "19:55:23", title: "87 Course Schedule, 88 Course Schedule II" },
        { time: "20:24:16", title: "89 Redundant Connection, 90 Number of Connected Components" },
        { time: "21:11:23", title: "91 Graph Valid Tree, 92 Word Ladder" },
        { time: "21:42:50", title: "93 Reconstruct Itinerary, 94 Min Cost to Connect All Points" },
        { time: "22:34:37", title: "95 Network Delay Time, 96 Swimming Pool" },
        { time: "23:14:40", title: "97 Alien Dictionary, 98 Cheapest Flights Within K Stops" },
        { time: "23:46:50", title: "99 Climbing Stairs, 100 Min Cost Climbing Stairs" },
        { time: "24:50:25", title: "101 House Robber, 102 House Robber II" },
        { time: "25:11:04", title: "103 Longest Palindromic Substring, 104 Palindromic Substrings" },
        { time: "25:39:56", title: "105 Decode Ways, 106 Coin Change" },
        { time: "26:10:23", title: "107 Maximum Product Subarray, 108 Word Break" },
        { time: "27:07:00", title: "109 Longest Increasing Subsequence, 110 Partition Equal Subset Sum" },
        { time: "28:45:52", title: "111 Unique Paths, 112 Longest Common Subsequence" },
        { time: "29:14:46", title: "113 Best Time to Buy And Sell Stock, 114 Coin Change II" },
        { time: "29:50:06", title: "115 Target Sum, 116 Interleaving String" },
        { time: "30:33:26", title: "117 Longest Increasing Path In a Matrix, 118 Distinct Subsequences" },
        { time: "31:11:49", title: "119 Edit Distance, 120 Burst Balloons" },
        { time: "31:54:37", title: "121 Regular Expression Matching, 122 Maximum Subarray" },
        { time: "32:31:46", title: "123 Jump Game, 124 Jump Game II" },
        { time: "33:07:02", title: "125 Gas Station, 126 Hand of Straights" },
        { time: "33:34:15", title: "127 Merge Triplets to Form Target Triplet, 128 Partition Labels" },
        { time: "33:55:28", title: "129 Valid Parenthesis String, 130 Insert Interval" },
        { time: "34:27:14", title: "131 Merge Intervals, 132 Non Overlapping Intervals" },
        { time: "35:00:49", title: "133 Meeting Rooms, 134 Meeting Rooms II" },
        { time: "35:26:18", title: "135 Minimum Interval to Include Each Query, 136 Rotate Image" },
        { time: "36:00:31", title: "137 Spiral Matrix, 138 Set Matrix Zeroes" },
        { time: "36:37:33", title: "139 Happy Number, 140 Plus One" },
        { time: "36:52:25", title: "141 Pow(x, n), 142 Multiply Strings" },
        { time: "37:11:53", title: "143 Detect Squares, 144 Single Number" },
        { time: "37:41:02", title: "145 Number of 1 Bits, 146 Counting Bits" },
        { time: "38:07:23", title: "147 Reverse Bits, 148 Missing Number" },
        { time: "38:35:03", title: "149 Sum of Two Integers, 150 Reverse Integer" }
      ]
    },
    {
      _id: "3",
      CourseName: "How to Create a Website – WordPress Tutorial for Beginners 2025",
      date: "2025-07-15",
      time: "01:00 PM",
      CourseImage: wordpressImage,
      videoLink: "https://youtu.be/R4v_7hh4Yys?si=LwTGHheTzTd2cJmx",
      contents: [
        { time: "0:01:09", title: "Introduction" },
        { time: "0:01:09", title: "What is WordPress?" },
        { time: "0:02:09", title: "Getting a Domain and Hosting" },
        { time: "0:04:08", title: "Installing WordPress" },
        { time: "0:04:08", title: "Setting Up Custom Email" },
        { time: "0:10:14", title: "Exploring WordPress Dashboard" },
        { time: "0:11:30", title: "Updating Settings" },
        { time: "0:12:43", title: "Installing Plugins" },
        { time: "0:15:26", title: "Installing Theme" },
        { time: "0:18:12", title: "Creating a Logo" },
        { time: "0:19:32", title: "Adding Logo to Website" },
        { time: "0:22:06", title: "Editing Site with Elementor" },
        { time: "0:33:08", title: "Adding Custom HTML to Site" },
        { time: "0:36:23", title: "Updating Menus" },
        { time: "0:37:24", title: "Adding a New Page" },
        { time: "0:43:20", title: "Customizing Page Name" },
        { time: "0:44:16", title: "Editing About Page" },
        { time: "0:45:18", title: "Editing Contact Page" },
        { time: "0:46:43", title: "Customizing Contact Form" },
        { time: "0:50:08", title: "Updating Page Footer" },
        { time: "0:51:31", title: "Making Site Responsive" },
        { time: "0:55:03", title: "Adding a Blog" },
        { time: "0:56:57", title: "Creating Posts with AI Content Creator" },
        { time: "0:59:56", title: "Customizing Blog" },
        { time: "1:02:09", title: "Conclusion" }
      ]
    },
    {
      _id: "4",
      CourseName: "React Native Full Course for Beginners",
      date: "2025-08-20",
      time: "11:00 AM",
      CourseImage: reactImage,
      videoLink: "https://youtu.be/sm5Y7Vtuihg?si=8VdZbK-6INFF3TP1",
      contents: [
        { time: "0:00:00", title: "Intro" },
        { time: "0:01:08", title: "Chapter 1: Start Here" },
        { time: "0:21:47", title: "Chapter 2: Build an App" },
        { time: "0:43:06", title: "Chapter 3: Navigation" },
        { time: "1:17:25", title: "Chapter 4: List Views" },
        { time: "2:05:47", title: "Chapter 5: CRUD App" },
        { time: "2:42:40", title: "Chapter 6: Data Storage" },
        { time: "3:20:20", title: "Chapter 7: Dynamic Routing" },
        { time: "4:02:34", title: "Chapter 8: EAS Development Builds" }
      ]
    },
    {
      _id: "5",
      CourseName: "Generative AI for Developers – Comprehensive Course",
      date: "2025-09-01",
      time: "02:00 PM",
      CourseImage: aiImage,
      videoLink: "https://youtu.be/F0GQ0l2NfHA?si=IJb5IxzEUDQLEUoz",
      contents: [
        { time: "0:00:00", title: "Course Introduction" },
        { time: "0:04:36", title: "Introduction of the Instructor" },
        { time: "0:05:52", title: "Introduction to Generative AI" },
        { time: "0:23:51", title: "End to end Generative AI Pipeline" },
        { time: "0:59:53", title: "Data Preprocessing & cleaning" },
        { time: "1:25:12", title: "Data representation & vectorization for the model training" },
        { time: "2:28:57", title: "Text Classification Practical" },
        { time: "2:42:05", title: "Introduction to Large Language Models & its architecture" },
        { time: "3:03:28", title: "In depth intuition of Transformer-Attention all your need Paper" },
        { time: "3:33:19", title: "How ChatGPT is trained" },
        { time: "3:43:44", title: "Introduction of Hugging Face" },
        { time: "3:56:02", title: "Hands-On Hugging Face - Transformers, HF Pipeline, Datasets, LLMs" },
        { time: "4:10:20", title: "Data processing,Tokenizing and Feature Extraction with hugging face" },
        { time: "4:17:34", title: "Fine-tuning using a pretrain models" },
        { time: "4:30:19", title: "Hugging face API key generation" },
        { time: "4:31:40", title: "Project: Text summarization with hugging face" },
        { time: "4:54:56", title: "Project: Text to Image generation with LLM with hugging face" },
        { time: "5:09:45", title: "Project: Text to speech generation with LLM with hugging face" },
        { time: "5:12:14", title: "Introduction to OpenAI" },
        { time: "5:21:12", title: "How to generate OpenAI API key?" },
        { time: "5:24:46", title: "Local Environment Setup" },
        { time: "5:27:13", title: "Hands on OpenAI - ChatCompletion API and Completion API" },
        { time: "5:54:44", title: "Function Calling in OpenAI" },
        { time: "6:09:11", title: "Project: Telegram bot using OpenAI" },
        { time: "6:44:18", title: "Project: Finetuning of GPT-3 model for text classification" },
        { time: "6:54:51", title: "Project: Audio Transcript Translation with Whishper" },
        { time: "7:12:54", title: "Project: Image genration with DALL-E" },
        { time: "7:18:22", title: "Mastering Prompt Engineering" },
        { time: "7:42:49", title: "The Complete Introduction to Vector Databases" },
        { time: "8:11:05", title: "Mastering Vector Databases with ChromaDB" },
        { time: "8:54:45", title: "Mastering Vector Databases with Pinecone" },
        { time: "9:19:39", title: "Mastering Vector Databases with Weaviate" },
        { time: "9:35:25", title: "Introduction & Installation and setup of langchain" },
        { time: "9:51:32", title: "Prompt Templates in Langchain" },
        { time: "9:55:33", title: "Chains in Langchain" },
        { time: "10:05:01", title: "Langchain Agents and Tools" },
        { time: "10:10:29", title: "Memory in Langchain" },
        { time: "10:17:41", title: "Documents Loader in Langchain" },
        { time: "10:21:25", title: "Multi-Dataframe Agents in Langchain" },
        { time: "10:25:50", title: "How to use Hugging face Open Source LLM with Langchain" },
        { time: "10:32:00", title: "Project: Interview Questions Creator Application" },
        { time: "11:29:26", title: "Project: Custom Website Chatbot" },
        { time: "11:46:21", title: "Introduction to Open Source LLMs - Llama" },
        { time: "12:20:39", title: "How to use open source llms with Langchain" },
        { time: "12:41:59", title: "Custom Website Chatbot using Open source LLMs" },
        { time: "13:12:41", title: "Open Source LLMs - Falcon" },
        { time: "13:29:11", title: "Introduction & Importance of RAG" },
        { time: "13:34:43", title: "RAG Practical demo" },
        { time: "13:45:10", title: "RAG Vs Fine-tuning" },
        { time: "13:48:31", title: "Build a Q&A App with RAG using Gemini Pro and Langchain" },
        { time: "13:57:35", title: "What is Fine Tuning? Parameter Efficient Fine-Tuning - LoRA & QLoRA" },
        { time: "14:10:07", title: "Fine-Tuning Meta Llama 2 on Custom Data" },
        { time: "14:28:55", title: "Introduction to LlamaIndex & end to end Demo" },
        { time: "14:57:41", title: "Open Source Mistral LLM with LlamaIndex" },
        { time: "15:09:57", title: "Project: Financial Stock Analysis using LlamaIndex" },
        { time: "15:23:51", title: "Project: End to End Medical Chatbot with LLM, Pinecone, LangChain" },
        { time: "16:34:38", title: "Project: End to End Source Code Analysis with LangChain, LLM and ChromaDB" },
        { time: "17:06:31", title: "Project: Implementing Zomato chatbot with Chainlit"  },
        { time: "17:40:11", title: "How to Deploy Generative AI Application as CICD on AWS" },
        { time: "18:10:32", title: "Introduction to LLMOps & Why we need it?" },
        { time: "18:35:06", title: "Generative AI with Google Cloud (Vertex AI) a LLMOps Platform" },
        { time: "18:49:37", title: "Vertex AI Hands-On on Google Cloud" },
        { time: "19:13:36", title: "Vertex AI Local Setup - Run Gemini Pro on Local Machine" },
        { time: "19:24:59", title: "RAG on Vertex AI with Vector Search and Gemini Pro" },
        { time: "19:41:06", title: "LLM powered application on Vertex AI" },
        { time: "19:44:57", title: "Fine-tuning Foundation Model on VertexAI" },
        { time: "19:57:51", title: "Introduction to AWS Bedrock" },
        { time: "20:14:52", title: "End to End RAG Project using AWS Bedrock" }
      ]
    },
    {
      _id: "6",
      CourseName: "Data Structures and Algorithms with Visualizations –  Full Course (Java)",
      date: "2025-11-05",
      time: "04:00 PM",
      CourseImage: dsaImage,
      videoLink: "https://www.youtube.com/watch?v=2ZLl8GAk1X4&t=12s",
      contents: [
        { time: "00:00:00", title: "Introduction" },
        { time: "00:03:46", title: "Introduction to Data Structures" },
        { time: "00:08:49", title: "Introduction to Algorithms" },
        { time: "00:19:43", title: "Time Complexity of an Algorithm" },
        { time: "00:25:05", title: "Space Complexity of an Algorithm" },
        { time: "00:27:14", title: "Asymptotic Analysis of an Algorithm" },
        { time: "00:29:43", title: "Asymptotic Notations" },
        { time: "00:39:06", title: "Analysis and Rules to calculate Big O notation" },
        { time: "01:06:16", title: "One-Dimensional Array" },
        { time: "01:32:38", title: "print elements of an Array" },
        { time: "01:44:29", title: "Remove Even Integers from an Array" },
        { time: "02:03:54", title: "Reverse an Array" },
        { time: "02:16:09", title: "find Minimum value in an Array" },
        { time: "02:28:13", title: "Find Second Maximum value in an Array" },
        { time: "02:41:03", title: "move Zeroes to end of an Array" },
        { time: "03:01:46", title: "resize an Array" },
        { time: "03:19:58", title: "Find the Missing Number in an Array" },
        { time: "03:34:08", title: "check if a given String is a Palindrome" },
        { time: "03:52:52", title: "Create a Singly Linked List" },
        { time: "04:02:58", title: "Print elements of a Singly Linked List" },
        { time: "04:13:11", title: "Find length of a Singly Linked List" },
        { time: "04:22:52", title: "Insert nodes in a Singly Linked List" },
        { time: "05:16:40", title: "Delete nodes of a Singly Linked List" },
        { time: "06:12:06", title: "search an element in a Singly Linked List" },
        { time: "06:22:42", title: "Reverse a Singly Linked List" },
        { time: "06:33:27", title: "find nth node from the end of a Singly Linked List" },
        { time: "06:46:43", title: "remove duplicate from sorted Singy Linked List" },
        { time: "06:57:51", title: "insert a node in a sorted Singly Linked List" },
        { time: "07:09:37", title: "remove a given key from Singly Linked List" },
        { time: "07:20:10", title: "detect a loop in a Singly Linked List" },
        { time: "07:36:58", title: "find start of a loop in a Singly Linked List" },
        { time: "07:57:54", title: "Why Floyd's Cycle Detection algorithm works" },
        { time: "08:17:23", title: "remove loop from a Singly Linked List" },
        { time: "08:37:36", title: "Merge Two Sorted Lists Question" },
        { time: "09:21:54", title: "LeetCode #2: Add Two Numbers" },
        { time: "09:41:53", title: "represent a Doubly Linked List" },
        { time: "09:46:06", title: "implement Doubly Linked List" },
        { time: "09:52:27", title: "print elements of a Doubly Linked List" },
        { time: "10:05:10", title: "insert node at the beginning of a Doubly Linked List" },
        { time: "10:15:25", title: "Insert node at the end of a Doubly Linked List" },
        { time: "10:25:50", title: "delete first node in a Doubly Linked List" },
        { time: "10:41:08", title: "delete last node in a Doubly Linked List" },
        { time: "10:55:49", title: "represent a Circular Singly Linked List" },
        { time: "11:03:46", title: "implement a Circular Singly Linked List" },
        { time: "11:11:20", title: "traverse and print a Circular Singly Linked List" },
        { time: "11:22:55", title: "insert node at the start of a Circular Singly Linked List" },
        { "time": "11:22:55", "title": "Insert node at the start of a Circular Singly Linked List" },
        { "time": "11:37:48", "title": "Insert node at the end of a Circular Singly Linked List" },
        { "time": "11:51:52", "title": "Remove first node from a Circular Singly Linked List" },
        { "time": "12:10:37", "title": "Stacks" },
        { "time": "13:08:22", "title": "Next Greater Element" },
        { "time": "13:29:44", "title": "Valid Parentheses problem (Balanced Brackets)" },
        { "time": "13:46:11", "title": "Represent a Queue" },
        { "time": "13:52:52", "title": "Implement a Queue" },
        { "time": "14:31:59", "title": "Generate Binary numbers from 1 to n using a Queue" },
        { "time": "14:50:36", "title": "Binary Trees" },
        { "time": "20:27:59", "title": "Search in a row and column wise sorted matrix" },
        { "time": "20:49:30", "title": "Print a given matrix in Spiral form" },
        { "time": "21:23:55", "title": "Introduction to Priority Queue and Binary Heap" },
        { "time": "21:32:00", "title": "Represent a Binary Heap" },
        { "time": "21:43:41", "title": "Implement Max Heap" },
        { "time": "21:56:25", "title": "Bottom-Up Reheapify (Swim) in Max Heap" },
        { "time": "22:09:30", "title": "Insert in a Max Heap" },
        { "time": "22:45:34", "title": "Top-Down Reheapify (Sink) in Max Heap" },
        { "time": "23:02:17", "title": "Delete max element in a Max Heap" },
        { "time": "23:25:57", "title": "Linear Search" },
        { "time": "23:35:47", "title": "Binary Search" },
        { "time": "23:51:38", "title": "Search Insert Position in a Sorted Array" },
        { "time": "24:13:22", "title": "Bubble Sort" },
        { "time": "24:51:29", "title": "Insertion Sort" },
        { "time": "25:33:57", "title": "Selection Sort Algorithm" },
        { "time": "26:16:06", "title": "Merge Two Sorted Arrays" },
        { "time": "26:53:01", "title": "Merge Sort" },
        { "time": "28:33:26", "title": "Sort an Array of 0’s, 1’s, and 2’s (Dutch National Flag Problem)" },
        { "time": "29:06:31", "title": "Quick Sort Algorithm" },
        { "time": "30:42:59", "title": "Squares of a Sorted Array" },
        { "time": "31:07:03", "title": "Rearrange Sorted Array in Max/Min form" },
        { "time": "31:38:01", "title": "Graphs" },
        { "time": "33:55:55", "title": "Number of Islands" },
        { "time": "34:43:56", "title": "Hashing and Hash Tables" },
        { "time": "37:33:21", "title": "Contains Duplicate" },
        { "time": "37:45:19", "title": "Introduction to Intervals and Overlapping Intervals" },
        { "time": "37:53:40", "title": "Merge Intervals" },
        { "time": "38:15:53", "title": "Insert Interval" },
        { "time": "38:40:02", "title": "Trie Data Structures" },
        { "time": "39:47:59", "title": "Dynamic Programming" },
        { "time": "41:26:02", "title": "Kadane's Algorithm for Maximum Sum Subarray" },
        { "time": "42:12:39", "title": "LeetCode: Two Sum" },
        { "time": "42:54:26", "title": "Is Valid Subsequence problem" },
        { "time": "43:22:23", "title": "First Non-Repeating Character in a String" },
        { "time": "43:48:45", "title": "Remove Vowels from a String" },
        { "time": "44:04:10", "title": "Reverse an Integer" },
        { "time": "44:23:13", "title": "Remove Element" },
        { "time": "44:40:54", "title": "Remove Duplicates from Sorted Array" },
        { "time": "44:58:57", "title": "Three Sum Problem Animation" },
        { "time": "45:22:37", "title": "Product of an Array except self" },
        { "time": "45:45:01", "title": "Sliding Window Maximum" },
        { "time": "46:32:09", "title": "Maximum Sum Subarray of Size K" },
        { "time": "46:59:45", "title": "LeetCode: Longest Substring Without Repeating Characters" },
        { "time": "47:24:15", "title": "LeetCode: Symmetric Tree" },
      ],
    },
  ]);


  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <button className={styles.dateButton}>
          <CalendarMonthIcon className={styles.icon} />
          Recommended Courses
        </button>
        <span className={styles.seeMore}>See More</span>
      </div>

      <div className={styles.CourseList}>
        {Courses.length > 0 ? (
          Courses.map(course => (
            <Course key={course._id} Course={course} />
          ))
        ) : (
          <Spinner />
        )}
      </div>
    </div>
  );
};

export default CourseSection;
